server:
  port: 9097

spring:
  application:
    name: Clear-Bill

  datasource:
    url: jdbc:mysql://localhost:3306/clearbill
    username: root
    password: pritam@123

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  #Mail Service
  mail:
    host: smtp.gmail.com
    port: 587
    username: jhantubala626@gmail.com
    password: gnjv oeqk gbss opki
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

file:
  logo: ./upload/logo
  product:
    image: ./upload/products


